List<String> chapter_ten_trans_sanskrit = [
  "śrībhagavān uvāca, bhūya eva mahābāho śṛṇu me paramaṃ vacaḥ, yat te 'haṃ prīyamāṇāya vakṣyāmi hitakāmyayā ॥",
  "na me viduḥ suragaṇāḥ prabhavaṃ na maharṣayaḥ ahamādir hi devānāṃ maharṣīṇāṃ ca sarvaśaḥ",
  "yo māmajam anādiṃ ca vetti lokamaheshvaram asammūḍhaḥ sa martyeṣu sarvapāpaiḥ pramucyate",
  "buddhir jnana masammohah kshama satyam damah shamah sukham duhkham bhavo 'bhavo bhayam cabhayam eva ca",
  "ahimsā samatā tuṣṭis tapo dānaṃ yaśo'yaśaḥ bhavanti bhāvā bhūtānāṃ matta eva pṛthag-vidhāḥ",
  "maharṣayaḥ saptapūrve caturāro manavastathā madbhāvā mānasā jātā yeṣāṃ loka imāḥ prajāḥ",
  "etāṁ vibhūtiṁ yogaṁ ca mama yo vetti tattvataḥ so'vikampena yogena yujyate nātra saṁśayaḥ",
  "aham sarvasya prabhavo mattah sarvam pravartate iti matva bhajante mam budha bhava-samanvitah",
  "Machchittā mad-gata-prāṇā bodhayantaḥ parasparam Kathayantaśca māṁ nityaṁ tuṣhyanti ca ramanti ca",
  "Teṣāṁ satata-yuktānāṁ bhajatāṁ prīti-pūrvakam Dadāmi buddhi-yogaṁ taṁ yena mām upayānti te.",
  "Teshām evānukampārtham aham ajñāna-jaṁ tamaḥ nāśayāmy ātma-bhāva-stho jñāna-dīpena bhāsvatā",
  "arjuna uvāca paraṁ brahma paraṁ dhāma pavitraṁ paramaṁ bhavān puruṣaṁ śāśvataṁ divyam ādi-devam ajaṁ vibhum",
  "āhus tvām ṛṣayaḥ sarve devarṣir nāradastathā asito devalo vyāsaḥ svayaṃ caiva bravīṣi me",
  "sarvam etad ritam manye yan mam vadasi keshava na hi te bhagavan vyaktim vidur deva na danavah",
  "Svayamevaatmanaatmaanam vetha twam purushottama Bhootabhaavana bhootesha devadeva jagatpate",
  "vakṭum arhasyaśeṣeṇa divyā hyātmavibhūtayaḥ yābhir vibhūtibhir lokān imāṃs tvaṃ vyāpya tiṣhṭhasi",
  "Katham vidyām ahaṁ yogiṁs tvaṁ sadā paricintayan Keṣu keṣu ca bhāveṣu cintyo'si bhagavan mayā.",
  "Vistareṇātmano yogaṁ vibhūtiṁ ca janārdana Bhūyaḥ kathaya tṛptir hi śṛṇvato nāsti me'mṛtam.",
  "Shri Bhagavan uvacha, hanta te kathayishyami divya hyatmavibhutayah, pradhanyatah kurushreshtha nastyanto vistarasyme.",
  "Aham atma gudakesha sarva-bhutashaya-sthitah, aham adishcha madhyam cha bhutanam anta eva cha.",
  "Adityanamaham vishnur jyotisham raviramshuman, marichir marutam asmi nakshatranamaham shashi.",
  "Vedanam samavedo'smi devanamasmi vasavah, indriyanam manashchasm bhutanam asmi chetana.",
  "Rudranam shankarashchasmi vitthesho yaksharakshasam, vasunam pavakashchasmi meruh shikharinamaham.",
  "Purodhasam cha mukhyam mam viddhi Partha Brihaspatim, senaninam aham Skandah sarasam asmi sagarah.",
  ];



List<String> chapter_ten_english = [
  "Śrī Bhagavān said: Again, O mighty-armed Arjuna, listen to My supreme word, which I shall speak to you who are dear to Me for your benefit.",
  "The demigods do not know my origin, nor do the great sages. I am the source of all demigods and sages.",
  "He who knows Me as the unborn, as the beginningless, as the Supreme Lord of all the worlds—he, undeluded among men, is freed from all sins.",
  "Buddhi (intellect), jnana (knowledge), asammoha (clarity), kshama (forgiveness), satya (truth), dama (self-control), shama (mental peace), sukha (happiness), dukha (distress), bhava (birth), abhava (death), bhaya (fear), and abhaya (fearlessness) - all these are nothing but the Supreme Being.",
  "Non-violence, equanimity, contentment, penance, charity, fame and infamy, these states of being of creatures arise from Me alone, separately.",
  "Seven great sages and four Manus, as well as their mental creations, have sprung from My mind, and all the creatures in these planets descend from them.",
  "Whoever understands in truth this my glory and yoga, becomes united with it unshakenly by means of unwavering yoga; there is no doubt about it.",
  "I am the source of all, from Me everything originates. The wise who know this worship Me with loving devotion.",
  "With their minds focused on me and their lives surrendered to me, enlightening one another and talking about me constantly, they are contented and delighted.",
  "To those who are constantly devoted and worship Me with love, I give the understanding by which they can come to Me.",
  "To show them special mercy, I, dwelling in their hearts, destroy with the shining lamp of knowledge the darkness born of ignorance.",
  "Arjuna said: \"You are the Supreme Brahman, the ultimate, the supreme abode and purifier, the Absolute Truth and the eternal divine person. You are the primal God, transcendental and original, and You are the unborn and all-pervading beauty.\"",
  "The sages, along with the divine sage Narada, Asita, Devala, and Vyasadeva, all proclaim this of You. And now You Yourself are declaring it to me.",
  "O Keshava, I believe that all that You have said to me is true. O Lord, neither the gods nor the demons comprehend Your manifestations.",
  "You, O Supreme Person, know Yourself by Yourself. You are the Lord of all creatures, the Creator of all, the God of gods, the Supreme controller of the universe.",
  "Please describe in detail Your divine glories, by which You pervade all these worlds by Your manifestations. O Lord, by expanding Your transdental form, You always reside in them.",
  "How should I know you, O Yogi, ever steadfast in concentration? In what aspects and forms are you to be meditated on, O blessed Lord?",
  "Tell me again in detail, O Janardana (Krishna), of Your mighty powers and glories, for I never tire of hearing Your nectar-like words.",
  "Shri Bhagavan said, \"O Kurusreshta (best among the Kurus)! I shall now tell you about the divine manifestations of the Self. However, there is no end to the extent of my greatness, and therefore, I shall only speak briefly.\"",
  "Lord Krishna said, \"O Arjuna, I am the Self, situated within all beings. I am the beginning, the middle, and also the end of all beings.\"",
  "Lord Krishna said, \"Among the Adityas, I am Vishnu; among the luminaries, I am the radiant sun. Among the Maruts, I am Marichi, and among the stars, I am the moon.\"",
  "Lord Krishna said, \"Among the Vedas, I am the Sama Veda; among the gods, I am Indra. Among the senses, I am the mind, and among living beings, I am consciousness.\"",
  "Lord Krishna said, \"Among the Rudras, I am Shankara; among the Yakshas and Rakshasas, I am the lord of wealth. Among the Vasus, I am the fire god, and among the mountains, I am Meru.\"",
  "Lord Krishna said, \"Know me to be the chief among priests, O Arjuna, and among the commanders of armies, I am Skanda. Among bodies of water, I am the ocean.\"",
];