List<String> chapter_13_trans_sanskrit = [
  "Arjuna uvācha: prakritim purusham chaiva kshetram kshetrajnameva cha etadveditumichchhāmi jñānam jñeyam cha keshava",
  "Shri Bhagavān uvācha: idam sharīram kaunteya kshetram ityabhidhīyate etad yo veti tam prāhuḥ kshetrajña iti tadvidaḥ",
  "kshetrajñam chāpi mām viddhi sarva-kshetreshu bhārata kshetra-kshetrajñayor jñānam yat tat jñānam matam mama",
  "tatksetram yacca yādrkca yadvikāri yataśca yat sa ca yo yatprabhāvaśca tatsamāsena me śrṇu",
  "rsibhirbahudhā gītaṁ chandobhir vividhaiḥ prthak brahmasūtrapadaiścaiva hetumadbhirviniścitaiḥ",
  "Mahābhūtānyahaṅkāro buddhiravyaktameva cha Indriyāṇi daśaikaṁ cha pañca chendriyagocarāḥ",
  "icchā dvesaḥ sukham duḥkham saṅghātaścetanā dhrtiḥ, etat ksetram samāsena savikāram udāhrtam",
  "amānitvam adambhitvam ahimsā ksāntir ārjavam ācāryopāsanam śaucaṁ sthairyam ātma-vinigrahaḥ",
  "Indriyartheshu vairagyam anahankara eva cha Janmamrityujaravyadhidukhadoshanudarshanam",
  "Asaktiranabhishvangah putradaragrihadeshhu Nityam cha samachittatvam ishtanishtopapattishu",
  "Mayi cha ananyayogena bhaktiravyabhicharini Viviktadeshasevitvam aratirjanasamsadi",
  "Adhyatma-jnananityatvam tattva-jnanartha-darshanam Etaj-jnanamiti proktam ajnanam yato'nyatha",
  "jñeyaḿ yattatpravakṣyāmi yajjñātvāmṛtam aśnute anādimat-paraḿ brahma na sat tan nāsad ucyate",
  "Sarvatah pāṇipādam tat sarvato 'kṣiśiromukham sarvatah śrutimal lōkē sarvam āvṛtya tiṣṭhati",
  "sarvendriya-gunabhasam sarvendriya-vivarjitam asaktam sarvabhricchaiva nirgunam guna-bhoktr ca",
  "Bahirantashcha bhutānāmacharam charam eva cha Sūkshmatvāttadavigñeyam dūrasthaṁ chāntike cha tat",
  "avibhaktam cha bhooteshu vibhaktamiva cha sthitam, bhoota-bhartr cha tajjneyam grasishnu prabhavishnu cha.",
  "jyotishamapi tajjyotistamasah paramuchyate, gyanam jneyam gyanagamyam hridi sarvasya vishthitam.",
  "iti kshetram tathaa gnanam jneyam choktam samaasatah, madbhakta etadvijnaaya madbhaavaayopapadyate.",
  "prakritim purusham chaiva viddhyanadi ubhavapi, vikaranshcha gunanshchaiva viddhi prakritisambhavan.",
  "karyakaranakartrutve hetuh prakritiruchyate, purushah sukhaduhkhanam bhoktrutve heturuchyate.",
  "purushah prakritistho hi bhungkte prakritijan gunan, karannam gunasango'sya sadasyoni janmasu.",
  " upadrashtaa anumantaa cha bhartaa bhoktaa maheshvarah paramaatmeti chaapyukto dehe'smin purushah parah",
  "Ya evam vetti purusham prakritim cha gunaih saha Sarvatha vartamano'pi na sa bhuyo'bhijayate",
];


List<String> chapter_13_english = [
"Arjuna said: O keshava, I wish to know about Prakriti (nature), Purusha (the soul), and kshetra (the field of activity) and also about the knower of the field.",
  "the Supreme Lord said: O son of kunti, this body is called the field, and the one who knows it is called the knower of the field by those who know the truth.",
  "know that knowledge to be of Me, which is the realization of the field and the knower of the field. O Arjuna, I am the knower of all fields of experience!",
  "O Arjuna, listen to me carefully and understand the essence of this knowledge. know that whatever the nature of the field is, whatever changes it undergoes, and whatever influences it, you should listen to all of it in summary from me.",
  "the Bhagavad Gita has been explained by various sages in different meters and in different ways. the essence of the Gita and the Brahmasutras has been established by solid reasoning and conclusive evidence.",
  "the five senses and the mind, along with the ego and intellect, Are the eightfold division of My material energy, O Arjuna.",
  "the desire for pleasure and aversion to pain, the union of consciousness and willpower, and perseverance, these constitute the field and its modifications.",
  "Humility, modesty, non-violence, forgiveness, honesty, service to the teacher, cleanliness, steadfastness, and self-control.",
  "One should develop detachment towards sensual pleasures and ego. By observing the problems of birth, death, old age, disease, and suffering, one should cultivate detachment. This verse emphasizes the importance of attaining mental peace and happiness, which is only possible by letting go of ego and developing detachment towards material pleasures.",
  "One should not be attached to children, wealth, home, and other possessions. One should always maintain equanimity of mind in all situations and treat the agreeable and disagreeable with equal detachment. This verse emphasizes that the source of happiness in human life is not wealth, children, or home, but rather it is achieved through a healthy mental state and maintaining equanimity in the face of life's problems.",
  "Devotion to me should be undivided and steadfast. One should live in a secluded place and be indifferent to the objects of the senses while carrying out their duties in the midst of people.",
  "Spiritual knowledge is eternal and the vision of truth is the aim of that knowledge. This is called knowledge, and anything else is ignorance.",
  "That which is to be known, I will declare to you, knowing which, one attains immortality. The supreme Brahman is without beginning. That non-existent (asat) never existed, nor will it ever exist.",
  "Everywhere are Its hands and feet, Its eyes, heads, and faces. Its ears are in all places, and it pervades everything in the universe.",
  "Appearing as the qualities of all the senses, yet devoid of all the senses, detached and all-pervading, without attributes and the enjoyer of attributes.",
  "The living beings, both moving and non-moving, are within and without, and they are also both subtle and gross. This truth is indeed difficult to understand, being both far away and very near.",
  "Undivided in all beings, yet appearing as if divided. The sustainer of all beings should be known as the consumer and the originator as well.",
  "Beyond the knowledge of astrology or any other form of knowledge, there exists a supreme knowledge that is beyond ignorance. This knowledge is seated in the hearts of all beings and is the object of knowledge, the knower, and the goal of knowledge itself.",
  "Thus the field, knowledge, and the knowable have been briefly described with reference to their essential nature. My devotee, by understanding this, attains to My being and becomes one with Me.",
  "Know nature and spirit to be without beginning. Understand that all modifications and qualities arise from nature.",
  "Nature is said to be the cause of the agency and the effect of the action. While the soul is said to be the cause of experiencing pleasure and pain.",
  "The individual soul, situated in nature, experiences the qualities born of nature. This is the cause of his birth in good and evil wombs.",
  "The witness, the permitter, the supporter, the enjoyer, and the great Lord Maheshvara, also called the Supreme Self - this higher self is said to reside within the body.",
  "One who understands the nature of the individual self and the material nature along with its modes, even while engaged in every kind of activity, does not take birth again in this material world.",
];