List<String> chapter_ten_trans_sanskrit = [
  "Arjuna uvācha: madanugrahāya paramaṁ guhyam adhyātmasaṁjñitam yat tvayoktaṁ vacas tena moho 'yaṁ vigato mama",
  "bhavāpyayau hi bhūtānāṁ śrutau vistaraśo mayā tvattaḥ kamalapatrākṣa māhātmyam api cāvyayam",
  "evam etad yathāttha tvam ātmānaṁ parameśvara draṣṭum icchāmi te rūpam aiśvaram puruṣottama",
  "manyase yadi tac chakyaṁ mayā draṣṭum iti prabho yogeśvara tato me tvam darśayātmānam avyayam",
  "śrī-bhagavān uvāca paśya me pārtha rūpāṇi śataśo'tha sahasraśaḥ nānā-vidhāni divyāni nānā-varṇākṛtīni ca",
  "paśyādityān vasūn rudrān aśvinau marutastathā bahūni-adṛṣṭa-pūrvāṇi paśyāścaryāṇi bhārata",
  "ihai-kastham jagat kṛtsnaḿ paśyādya sakalācarām mama dehe gudākeśa yac cānyad draṣṭum icchasi",
  "na tu māḿ śakyase draṣṭum anenaiva svacakṣuṣā divyaḿ dadāmi te cakṣuḥ pasyame yogam aiśvaram",
  "sañjaya uvāca evam uktvā tato rājan mahā-yogeśvaro hariḥ darśayām āsa pārthāya paramaḿ rūpam aiśvaram",
  "aneka-vaktra-nayanam aneka-adbhuta-darshanam aneka-divya-abharanam divya-aneka-udyata-ayudham",
  "Divyam ālyāmbara-dharam divya-gandhānulepanam, Sarvāścaryamayaṁ devam anantam viśvato-mukham",
  "divi sūryasahasrasya bhavedyugapadutthitā, yadi bhāḥ sadṛśī sā syādbhāsastasya mahātmanaḥ",
  "tatraikasthaṁ jagatkṛtsnaṁ pravibhaktamanekadhā, apaśyaddevadevasya śarīre pāṇḍavastadā ",
  "Tatah sa vismayavishto hrishhtaroma dhananjayah, pranamya shirasa devam kritanjali rabhashata.",
  "Arjuna uvācha paśyāmi devāṁs tava deva dehe sarvāṁs tathā bhūta-viśheṣha-saṅghān brahmāṇam īśhaṁ kamalāsana-sthaṁ ṛiṣhīṁśh cha sarvān uragānśhcha divyān.",
  "Anekabāhūdaravaktranetram pashyāmi tvām sarvato’nantarūpam nāntaṃ na madhyaṃ na punastavādim pashyāmi viśveśvara viśvarūpa",
  "kirīṭinaṁ gadinaṁ cakriṇaṁ ca tejorāśiṁ sarvato dīptimantam paśyāmi tvāṁ durnirīkṣyaṁ samantād dīptānalārkadyutimaprameyam",
  "tvam akṣaraṁ paramaṁ veditavyaṁ tvam asya viśvasya paraṁ nidhānam tvam avyayaḥ śāśvatadharmagoptā sanātanastvaṁ puruṣo mato me",
  "anādi-madhyāntam anantavīrya-mantabāhuṁ śaśisūrya-netram paśyāmi tvāṁ dīptahutāśa-vaktraṁ svatejasā viśvam idaṁ tapantam",
  "dyāvāpṛthivyōridamantarṁ hi vyāptaṁ tvayaikena diśaśca sarvāḥ dṛṣṭvādbhutaṁ rūpamugraṁ tavedaṁ loktrayaṁ pravyathitaṁ mahātman",
  "Amii hi tvaam sura-sanghaa vishanti Kechid bhiitaah praannjalayo griinanti Svastiityuktva maharshi-siddha-sanghaah Stuvanti tvaam stutibhih pushkalaabhih",
  "Rudraadityaa vasavo ye cha saadhyaa Viswe'shwinou marutashcho'shmapaashcha  Gandharva-yakshaasura-siddha-sanghaa Veekshante tvaam vismitaashchaiva sarve",
  "Roopam mahatte bahu vaktra netram Mahabaho bahubahuuru paadam, Bahoodaram bahudamshtra karalam Drushtwaa lokah pravyathitaas tathaa'ham",
  "nabhaspr̥śaṁ dīptamanekavarṇaṁ vyāttānanam dīptaviśālanetram, dṛṣṭvā hi tvāṁ pravyathitāntarātmā dhṛtiṁ na vindāmi śamaṁ cha viṣṇo",
  "daṃṣṭrākarālāni ca te mukhāni dṛṣṭvaiva kālānalasannibhāni, diśo na jāne na labhe ca śarma prasīda deveśa jagannivāsa",
  "amī ca tvāṃ dhṛtarāṣṭrasya putrāḥ sarve sahaivāvanipālasaṅghaiḥ, bhīṣmo droṇaḥ sūtaputrastathāsau sahāsmadīyairapi yodhamukhyaiḥ ",
  "vaktraaNi te tvaramaaNaa vishanti damshTraakaraalaani bhayaanakaani, kechid vilagnaa dashanaantareshu sandR^ishyante chuurNitairutamaaN^gaiH",
  "yathā nadīnāṃ bahavo'mbuvegāḥ samudramevābhimukhā dravanti, tathā tavāmī naralokavīrā viśanti vaktrāṇyabhivijvalanti",
  "yathā pradīptaṃ jvalanaṃ patan̄gā viśanti nāśāya samṛddhavegāḥ, tathaiva nāśāya viśanti lokāḥ tavāpi vakṭrāṇi samṛddhavegāḥ",
  "lelihyase grasamānaḥ samantāl- lokān samagrān vadanair jvaladbhiḥ, tejobhir āpūrya jagat samagraṃ bhāsas tavo'grāḥ pratapanti viṣṇo",
  "aakhyaahi me ko bhavaanugrahaarupo namo.astu te devavara praseeda vijnaatumicchaami bhavantamaadyam na hi prajaanaami tava pravrittima.",
  "śrībhagavānuvāca, kālo'smi lokakṣayakṛtpravṛddho lokānsamāhartumiha pravṛttaḥ, ṛte'pi tvāṃ na bhaviṣyanti sarve ye'vasthitāḥ praty-anīkeṣu yodhāḥ",
  "Tasmāttvamuttishṭha yasho labhasva Jitvā śatrūn bhuńkṣva rājyam samṛddham Mayaivaitē nihatāḥ pūrvamēva Nimittamātram bhava savyasācin.",
  "Dronam cha Bhishmam cha Jayadratham cha, Karnam tathanyanapi yodhaviran, Mayaa hataamstwam jahi ma vyathishthaa, Yudhyaswa jetasi rane sapatnaan.",
  "Sanjaya uvacha, Etacchrutva vachanam keshavasya, Kritanjalirvepamaanah kiriti, Namaskritwa bhooya evaha krishnam, Sagadgadam bheetabheetah pranamya.",
  "arjuna uvāca sthāne hṛṣīkeśa tava prakīrtyā jagat prahṛṣyatyanurajyate ca rakṣāṃsi bhītāni diśo dravanti sarve namasyanti ca siddha-saṅghāḥ",
  "kasmāt cha te na nameran mahātman garīyase brahmaṇo'py ādi-kartre ananta deveśa jagannivāsa tvam akṣaraṁ sad-asat tat paraṁ yat",
  "tva-mādidevaḥ puruṣaḥ purāṇas tva-masya viśvasya paraṁ nidhānam vettāsi vedyaṁ ca paraṁ ca dhāma tvayā tataḿ viśvam anantarūpa",
  "vāyu r yamo'gnir varuṇaḥ śaśāṅkaḥ prajāpati stvaṁ prapitāmahaśca, namo namaste'stu sahasrakṛtvaḥ punaśca bhūyo'pi namo namaste",
  "namah purastād atha pṛṣṭha-tas te namo 'stu te sarvata eva sarva ananta-vīryāmita-vikrama-stvaḿ sarvaṁ samāpnoṣi tato 'si sarvaḥ",
  "sakheti matvā prasabhaṁ yad uktaṁ he kṛṣṇa he yādava he sakheti ajānatā mahimānaṁ tavedaṁ mayā pramādāt praṇayena vāpi",
  "yachchavahāsārtham asatkṛto'si vihāraśhayyāsana-bhojaneṣhu eko'thavāpyachyuta tatsamakṣhaṁ tatkṣhāmaye tvām aham aprameyam",
  "Pitāsi lokasya carācasya tvamasya pūjyaśca gururgarīyān na tvatsamo'styabhyadhikaḥ kuto'nyo lokatraye'pyapratimaprabhāva",

];


List<String> chapter_ten_english = [
  "Arjuna said: For the benefit of me, please reveal the supreme, secret knowledge of the self. With those words spoken by you, this delusion of mine has been dispelled.",
  "The cycle of birth and death of all beings has its origin in me. This is revealed in the scriptures in great detail. You are also indestructible, O lotus-eyed one, and your glories are limitless.",
  "O Supreme Lord, as You have described Yourself, I wish to see You in that form. O best of persons, if You think that I am able to behold Your cosmic form, then kindly show me that unlimited, supreme, divine form.",
  "O Lord of yoga, if You think that I am capable of seeing it, then please show me Your imperishable self.",
  "The Supreme Lord said: Behold, O Arjuna, My forms by the hundreds and thousands, in many different divine varieties, of various colors, shapes, and sizes.",
  "Behold, O Arjuna, the Adityas, the Vasus, the Rudras, the Asvins, and the Maruts. Behold many wondrous things never before seen, O Arjuna.",
  "Behold now, O Arjuna, the entire universe, with everything moving and stationary, situated in one place within my body. But you cannot see Me with your physical eyes; therefore, I give you divine eyes, so that you may behold my majestic opulence.",
  "But you cannot see Me with your ordinary eyes. Therefore, I give you divine eyes to see my majestic power and glory.",
  "Sanjaya said: O King, having spoken thus, the great Lord of Yoga, Hari (Krishna), showed Arjuna His universal form as the supreme, majestic, and divine.",
  "Many mouths and eyes had He, manifold were His wonderful sights, Many divine ornaments decked Him, and divine weapons shone bright.",
  "His divine form adorned with divine garlands and clothing, He wears divine fragrances and is resplendent with every kind of wonder. He is the infinite divine being, the beginning, middle, and end of everything, With faces on all sides, He is omnipresent and all-pervading.",
  "If a thousand suns were to rise in the sky simultaneously, their radiance might resemble the effulgence of the Supreme Person in that universal form.",
  "There he saw the entire universe divided in many ways, in the body of the God of gods, Pandava, at that time",
  "Then, filled with wonder and with hairs standing on end, Arjuna bowed his head to the Lord and spoke with folded hands:",
  "Arjuna said, \"I behold all the gods in Your body, O Lord, as also hosts of diverse classes of beings. Brahma the Creator, seated on his lotus-seat, and all the Rishis and divine serpents, I see in You.\"",
  "I see You with countless arms, stomachs, faces, and eyes. You are present everywhere and have infinite forms. I see no beginning, middle, or end to Your being. O Lord of the universe, I see You as the embodiment of everything.",
  "I see you with a crown, mace, discus, radiance, and blazing light from all sides. I see you like an immeasurable, dazzling fire and sun, difficult to look at from all directions.",
  "You are the imperishable, supreme, and should be known. You are the ultimate support of this universe. You are unchanging, eternal, the protector of dharma. To me, you are the eternal Person, this is my belief.",
  "You are without beginning, middle or end, of infinite power, with arms extending everywhere, and eyes as bright as the sun and moon. I see you, with your mouth aglow with the flames of sacrifice,burning this entire universe with your own radiance.",
  "O great soul! You alone pervade the expanse between heaven and earth, and all directions are encompassed by you. Beholding your wondrous and fierce form,the three worlds tremble in agitation.",
  "Some in the assemblage of celestial beings bow to You, while others extol You in fear. The company of sages and perfected beings proclaims \"All is well!\" and offers praise in various hymns.",
  "The Rudras, Adityas, Vasus, Sadhyas, Visvadevas, the two Asvins, the Maruts, and the Usmapas, and hosts of Gandharvas, Yakshas, Asuras, and Siddhas, all gaze at You in wonder.",
  "Your form is great, with many faces and eyes, Oh mighty-armed one, with many arms, thighs, feet, bellies, and fearful teeth; the worlds are frightened on seeing you like this, so am I.",
  "Your form is difficult to see because of its glaring effulgence, spreading on all sides like blazing fire or the immeasurable radiance of the sun. Yet I see this glowing form everywhere, adorned with various crowns, clubs, and discs, O Vishnu.",
   "Seeing your fearsome teeth and terrifying mouth resembling the fire of time, I do not know the directions nor do I find any solace. O Devesha, O Jagannivasa, be pleased and have mercy on me.",
  "All these sons of Dhritarashtra, along with their allied kings and Bhisma, Drona and Karna, and all our soldiers, are rushing into Your fearful mouths. And some I see trapped with heads smashed between Your teeth.",
  "Your fearful teeth and faces, looking so terrible, are scaring me. The sons of Dhritarashtra and all the kings present here with their armies are looking at You in fear. Even some of the great sages are bewildered when they see Your mouths with their fearful teeth and faces. O Lord of the universe, please be merciful to me. I cannot withstand the sight of Your fearful and gigantic form.",
  "Just as many streams of water rush towards the ocean, similarly these heroes of the human world enter into your blazing mouths.",
  "Just as moths rush to a blazing flame with great speed to meet their destruction, in the same way, the people's faces enter your burning and shining mouths with great speed for their destruction.",
  "You, who lick (devour) all the worlds, with your flaming mouths, you who fill the entire universe with your radiant energy, your terrible and bright rays burn forth, O Vishnu.",
  "Tell me who you are, O fierce form. Salutations to you, O supreme Lord. Have mercy on me. I desire to know you, the original Being. I do not understand your deeds.",
  "The Supreme Personality of Godhead said: Time I am, destroyer of the worlds, and I have come to engage all people. With the exception of you [the Pandavas], all the soldiers here on both sides will be slain.",
  "Therefore, arise and obtain glory. Conquer your enemies and enjoy prosperous kingdom. They are already slain by me, you are only an instrument of the battle, O Arjuna, the skilled archer.",
  "Therefore, strike down Drona, Bhishma, Jayadratha, Karna, and other brave warriors who are already slain by Me. Do not be disturbed by the illusion that you are the killer. Fight and you will conquer your enemies on the battlefield.",
  "Sanjaya said, Hearing these words of Keshava, the crown-wearing Arjuna, with joined palms, trembling, offered obeisance again and again, with a choked voice, and in fear.",
  "Arjuna said: O Hrishikesha, by praising You, the world rejoices and is filled with joy. All the directions, O Lord, fearfully run away, and the perfected ones bow down to You. ",
  "Why should they not offer their reverence to you, O Great One, who are greater even than Brahman, the primal cause? O limitless One, God of gods, abode of the universe, you are the imperishable, the Absolute Truth, which is both being and non-being.",
  "You are the primal God, the ancient being, the ultimate refuge of this universe. You are the knower, the knowable, and the supreme abode. By You, the universe is pervaded, O infinite form!",
  "Salutations to Vayu, Yama, Agni, Varuna, Chandra (the moon), Prajapati (the creator), and to Pitamaha (the great-grandfather). Salutations to you a thousand times, and again and yet again, salutations to you.",
  "Salutations to You in front and behind, O Supreme Being! Salutations to You on all sides, O All! O Infinite in Your power and prowess, You pervade all, and therefore You are everything.",
  "Thinking of You as my friend, I have rashly addressed You 'O Krishna,' 'O Yadava,' 'O my friend,' not knowing Your glories. Please forgive whatever I may have done in madness or in love. I have dishonored You many times, jesting as we relaxed, lay on the same bed, or sat or ate together, sometimes alone and sometimes in front of many friends. O infallible one, please excuse me for all those offenses.",
  "Whatever disrespect has been shown to You by me through ignorance, while playing, sitting, or eating, alone or in the presence of others, please forgive me for all that, O Achyuta, who is immeasurable.",
  "You are the father of this universe, the mother, the supporter, and the grandsire. You are the object of worship, the supreme guru, and the greatest benefactor. No one is equal to You, nor can anyone be greater than You. In the three worlds, there is no one who can attain a position superior to Yours.",
];