List<String> chapter_six_trans_sanskrit = [
  "Shri Bhagavanuvaacha, Anashritah karmaphalam karyam karma karoti yah Sa sannyasi cha yogi cha na niragnirna chaakriyah ",
  "yam sannyasamiti prāhuryogam tam viddhi pāndava na hyasannyasta-sankalpo yogi bhavati kashchana",
  "arurukshormuner yogaṃ karma kāraṇam uchyate yogārūḍhasya tasyaiva śamaḥ kāraṇam uchyate",
  "yadā hi nendriyārtheṣu na karmasvanuṣajjate sarva-saṅkalpa-sannyāsī yogārūḍhas tadocyate",
  "uddhared atmanatmanam naatmanam avasaadayet, aatmaiva hyaatmano bandhuraatmaiva ripuraatmanah",
  "bandhur ātmātmanas tasya yenātmāivātmanā jitaḥ, anātmanas tu śatrutve vartetātmāiva śatruvat",
  "jitātmanaḥ praśāntasya paramātmā samāhitaḥ śītoṣṇa-sukha-duḥkheṣu tathā mānāpamānayoḥ",
  "jñāna-vijñāna-tṛptātmā kūṭastho vijitendriyaḥ yukta ityucyate yogī samaloṣṭāśma-kāñcanaḥ",
  "suhṛnmitrāryudāsīnamadhyastha-dveṣyabandhuṣu sādhuṣvapi ca pāpeṣu sama-buddhirviśiṣyate",
  "yogī yuñjīta satatam ātmānaṁ rahasi sthitaḥ ekākī yatacittātmā nirāśīr aparigrahaḥ",
  "shucau deshe pratiShThaapya sthiramaasanamaatmanaH naatyucchritaM naatiniichaM chailaajinakuShottharam",
  "Tatraikāgraṃ manaḥ kṛtvā yatacittendriyakriyaḥ Upaviśyāsane yuñjyād yogam ātma viśuddhaye",
  "Samam kāyaśirogrīvam dhārayannacalam sthiraḥ, samprekṣya nāsikāgram svam diśaścānavalokayan.",
  "prashāntātmā vigatabhīr brahmachārivr̥te sthitaḥ manaḥ saṃyamya macchitto yukta āsīta matparaḥ",
  "yuñjann evaṁ sadātmānaṁ yogī niyatamānasaḥ śāntiṁ nirvāṇa-paramāṁ matsaṁsthāmadhigacchati",
  "Naatyashnatastu yogosti na chaikaantamanashnatah, Na chaatisvapnashilasya jaagrito naiva chaarjuna.",
  "Yuktāhāra-vihārasya yukta-cheṣṭasya karmasu Yuktasvapnāvabodhasya yogaḥ bhavati duḥkha-hā",
  "Yadā viṇiyataṁ cittam ātmanyevāvatuniṣṭhate Niḥspṛhaḥ sarva-kāmebhyo yukta ityucyate tadā",
  "Yathā dīpo nivātastho neṅgate sopamā smṛtā Yogino yatacittasya yuñjato yogam ātmanaḥ",
  "Yatroparamate cittaṁ niruddhaṁ yogasevayā Yatra caivātmanātmānaṁ paśyannātmani tuṣyati",
  "Sukhamātyantikaṁ yat tad buddhigrāhyam atīndriyam Vetti yatra na caivāyaṁ sthitaś calati tattvataḥ",
  "Yaṁ labdhvā cāparaṁ lābhaṁ manyate nādhikaṁ tataḥ Yasmin sthito na duḥkhena guruṇāpi vicalyate",
  "Tam vidyaad dukha-samyo-ga-viyogam yogasamjnitam Sa nishchayena yoktavyo yogo'nirvinnachetasaa.",
  "Sankalpa prabhavan kaman tyaktva sarvan asheshatah, manasaivendriya-gramam viniyamya samantatah.",
  "shanaih shanairuparamed buddhyaa dhritigriheetayaa aatmasamstham manah kritwaa na kinchidapi chintayet",
  "yato yato nishcharati manashchanchalamasthiram tatas tato niyamyaitadatmanyeva vasham nayet",
  "prashantamanasam hyenam yoginam sukhmuttamam upaiti shantarajasam brahmabhutamakalmasham",
  "yuñjann evaṁ sadātmānaṁ yogī vigatakalmaṣaḥ sukena brahma-saṁsparśam atyantaṁ sukham aśnute",
  "Sarva-bhūta-stham ātmānam, sarva-bhūtāni cātmani, īkṣate yoga-yuktātmā, sarvatra samadarśanaḥ.",
  "Yo māṁ paśyati sarvatra, sarvaṁ ca mayi paśyati, tasyāhaṁ na praṇaśyāmi, sa ca me na praṇaśyati.",
  "Sarvabhūta-sthitaṁ yo māṁ bhajatyekatvamāsthitaḥ, sarvathā vartamāno'pi sa yogī mayi vartate.",
  "ātmaupamyena sarvatra samaṃ paśyati yo'rjuna, sukhaṃ vā yadi vā duḥkhaṃ sa yogī paramo mataḥ"
  ];


List<String> chapter_six_english = [
"Shri Bhagavan said: One who performs actions without desiring the fruits of those actions is both a sannyasi (renunciate) and a yogi, and not one who simply gives up the fire sacrifice or one who is inactive.",
"O Pandava, understand that the renunciation of actions is known as sannyasa and the practice of yoga is said to be the means. No one can become a yogi without renouncing the desire for the fruits of their actions.",
  "The practice of yoga is said to be the means to attain the highest goal. For one who has attained yoga, tranquility is said to be the means.",
  "For when one does not get attached to sense objects or actions, then one is said to have attained yoga. One who has attained inner peace by renouncing all desires is said to be established in yoga.",
  "One must elevate oneself by one's own mind, not degrade oneself. The mind is the friend of the conditioned soul, and his enemy as well.",
"One must deliver oneself with the help of one's own mind, and not degrade oneself. The mind is the friend of the conditioned soul, and his enemy as well.",
"The Supreme Being is steady in the consciousness of one who has conquered the mind and senses, and is calm in heat and cold, pleasure and pain, and honor and dishonor.",
  "A person who is satisfied with knowledge and realization, who remains steady and undisturbed in all situations, who has control over the senses, and to whom a clod of earth, a stone, and gold are all the same, is said to be a yogi, and is in a state of perfect union.",
  "He who is the same towards friend and foe, in honour and dishonour, in cold and heat, in pain and pleasure, and who is free from attachment, is said to have a stable mind. Such a person is superior to those who have a discriminating intellect, and who are attached to the fruit of their actions.",
  "The yogi, constantly engaged in meditation, with mind fixed on the Supreme, attains to peace and the highest bliss. The yogi, being self-controlled, serene and steadfast, with mind and intellect fixed on the Supreme Lord, is said to be in constant communion with Him.",
  "One should establish a steady seat for oneself in a clean and pure place, neither too high nor too low, and covered with a cloth, skin, and kusha grass.",
  "Keeping the mind focused in one place, with the actions of the senses and the mind controlled, let the yogi practice yoga for self-purification, seated on a firm and clean seat.",
  "Keeping the body, neck, and head erect and still, and gazing at the tip of one's own nose, without looking around in all directions.",
  "One who is peaceful, free from fear, and established in celibacy, is said to be in a state of steady wisdom. Such a person's mind should be restrained and focused on Me, and they should be devoted to Me.",
  "Thus, always keeping the mind fixed on Me with supreme devotion, the yogi of unified consciousness attains Me, the supreme divine personality, the source of all beings, situated in the eternal imperishable abode of transcendental bliss.",
  "There is no possibility of one becoming a yogi, O Arjuna, if he eats too much or eats too little, sleeps too much or does not sleep enough.",
  "Yoga (union with the divine) destroys suffering, for one who is moderate in eating and recreation, regulated in actions, and sleeping and waking, and engaged in positive actions.",
  "When the mind, restrained from material activities, becomes still by the practice of yoga, then the yogi is able to behold the Self through the purified mind, and he rejoices in the inner joy. He is satisfied within himself, and thus he is said to be in constant union with the Supreme Personality of Godhead.",
  "Just as a lamp in a windless place flickers not, so the transcendentalist, who controls his mind, body and activities, is not affected by the material modes of nature, even while performing actions.",
  "Wherever the mind wanders, restless and diffuse in its search for satisfaction without, lead it within; train it to rest in the Self. Such an unswerving concentration is called yoga. One finds ultimate satisfaction in the Self alone.",
  "That which is perceivable by the mind, which is supremely blissful, and which is beyond the grasp of the senses, is known as the supreme happiness. Having realized this happiness, the self-controlled yogi neither desires anything else nor grieves for anything that he may have lost.",
  " One who believes that gaining a certain thing will make them happier than obtaining something else, is mistaken. One who remains steady and unperturbed even when facing difficulties, is not shaken even by the greatest sorrow.",
  "One should understand that yoga is the disconnection from the union with suffering. With a steadfast mind, one should engage in yoga with determination.",
  "One who has given up all desires that arise in the mind and has completely restrained the senses, by the power of determination; with the mind fixed on the Supreme Being, is called undeviating in yoga.",
  "Gradually, with steady and focused intelligence and determination, one should withdraw oneself from all material desires and cravings, and bring the mind to rest upon the self within. One should think of nothing else.",
  "Wherever the mind wanders restlessly and unsteady, one should bring it back and concentrate it upon the self alone.",
  "This yogi, with a tranquil mind, attains the supreme happiness, where the passion and anger have been subdued, and has become free from sin, and has realized the Brahman, the ultimate reality.",
  "The yogi who constantly practices this, free from all impurities, with a well-controlled mind, easily attains the supreme happiness of contact with Brahman.",
  " A yogi who is united with the Lord through yoga sees the Self present in all beings and all beings present within the Self. Such a person sees everything with an equal vision.",
  "He who sees Me in all things and sees all things in Me, I never leave him nor does he ever leave Me.",
  "One who worships Me, who is present in all beings, realizing the oneness of all existence, remains in Me, regardless of how they appear to live in this world.",
  "He who sees Me everywhere and sees everything in Me, he is never lost to Me, nor am I ever lost to him. He who is steadfast in this yogic vision, O Arjuna, sees the Self abiding in all beings, and all beings in the Self, and he sees the same everywhere.",

];
