List<String> chapter_18_trans_sanskrit = [
  "Arjuna uvācha: saṁnyāsasya mahā-bāho tattvam icchāmi veditum tyāgasya ca hṛṣīkeśa pṛthak keśiṇiśūdana",
  "Shrī Bhagavān uvācha: kāmyānāṁ karmaṇāṁ nyāsaṁ sannyāsaṁ kavayo viduḥ sarva-karma-phala-tyāgaṁ prāhus tyāgaṁ vichakṣaṇāh",
  "tyājyaṁ doṣa-vad ity eke karma prāhur manīṣiṇaḥ yajña-dāna-tapaḥ-karma na tyājyam iti cāpare",
  "nishchayaṁ śhṛiṇu me tatra tyāge bharata-sattama tyāgo hi puruṣha-vyāghra trividhaḥ samprakīrtitaḥ",
  "yajñadāna-tapaḥ-karma na tyājyaṁ kāryam eva tat yajño dānaṁ tapaś chaiva pāvanāni manīṣhiṇām",
  "etānyapi tu karmāṇi saṅgaṁ tyaktvā phalāni cha kartavyānīti me pārtha niśchitaṁ matam uttamam",
  "niyatasya tu sannyāsaḥ karmaṇo nopapadyate mohāt tasya parityāgas tāmasaḥ parikīrtitaḥ",
  "duḥkham ityeva yat karma kāya-kleśa-bhayāt tyajet sa kṛtvā rājasaṁ tyāgaṁ naiva tyāga-phalaṁ labhet",
  "Kāryamityeva yatkarma niyataṁ kriyate 'rjuna Saṅgaṁ tyaktvā phalaṁ caiva sa tyāgaḥ sāttviko mataḥ",
  "Na dveṣṭyakushalaṁ karma kushale nānuṣajjate Tyāgī sattvasamāviṣṭo medhāvī chinnasaṁśayaḥ",
  "Na hi dehabhṛtā śakyaṁ tyaktuṁ karmāṇy-aśeṣataḥ Yas tu karmaphala-tyāgī sa tyāgītyabhidhīyate",
  "Aniṣṭam-iṣṭaṁ miśraṁ cha trividhaṁ karmaṇaḥ phalam Bhavaty-atyāgināṁ pretya na tu sannyāsināṁ kvachit",
  "Pañcaitāni mahābāho kāraṇāni nibodha me Sāṅkhye kṛtānte proktāni siddhaye sarvakarmaṇām",
  "Adhiṣṭhānaṁ tathā kartā karaṇaṁ cha pṛthagvidham Vividhāśhcha pṛthak cheṣhṭā daivaṁ chaivātra pañcha",
  "śarīravāṅmanobhiryat karma prārabhate naraḥ nyāyyaṁ vā viparītaṁ vā pañcaite tasya hetavaḥ",
  "tatraivaṁ sati kartāramātmānaṁ kevalaṁ tu yaḥ paśyatyakṛtabuddhitvānna sa paśyati durmatiḥ",
  "yasya nāhaṅkṛto bhāvo buddhir-yasya na lipyate hatvā'pi sa imāṁllokānna hanti na nibadhyate",
  "jñānaṁ jñeyaṁ parijñātā trividhā karmachodanā karaṇaṁ karma karteti trividhaḥ karmasaṅgrahaḥ",
  "jñānaṁ karma cha kartā cha tridhaiva guṇabhedataḥ prochyate guṇasaṅkhyāne yathāvachchhṛṇu tānyapi",
  "sarvabhūteṣu yenaikaṁ bhāvamavyayamīkṣate avibhaktaṁ vibhakteṣu tajjñānaṁ viddhi sāttvikam",
  "pṛthaktvena tu yajjñānaṁ nānābhāvān pṛthagvidhān vetti sarveṣu bhūteṣu tajjñānaṁ viddhi rājasam",
  "yattu kṛtsnavadekasminkārye saktamahaitukam atattvārthavadalpaṁ cha tattāmasamudāhṛtam",
  "niyataṁ saṅgarahitam-arāgadveṣataḥ kṛtam aphalaprepsunā karma yattat sāttvikamucyate",
  "yattu kāmepsunā karma sāhaṅkāreṇa vā punaḥ kriyate bahulāyāsaṁ tad rājasamudāhṛtam",
  "anubandhaṁ kṣayaṁ hiṁsāmanapekṣya cha pauruṣam mohād ārabhyate karma yattat tāmasamucyate",
  "muktasaṅgo'nahaṁvādī dhṛtyutsāhasamanvitaḥ siddhyasiddhyor nirvikāraḥ kartā sāttvika uchyate",
  "rāgī karmaphalaprepsur lubdho hiṁsātmako 'śuciḥ harṣaśokānvitaḥ kartā rājasaḥ parikīrtitaḥ",
  "ayuktaḥ prākṛtaḥ stabdhaḥ śaṭho naiṣkṛtiko'lasaḥ viṣādī dīrghasūtrī cha kartā tāmasa uchyate",
  "buddher bhedaṁ dhṛteśh chaiva guṇatas trividhaṁ śṛṇu prochyamānam aśeṣeṇa pṛthaktvena dhanañjaya",
  "pravṛttiṁ cha nivṛttiṁ cha kāryākārye bhayābhaye bandhaṁ mokṣhaṁ cha yā vetti buddhiḥ sā pārtha sāttvikī",
  "yayā dharmam adharmam cha kāryam chākāryam eva cha ayathāvad prajānāti buddhiḥ sā pārtha rājasī",
  "adharmaṁ dharmam iti yā manyate tamasāvṛtā sarvārthān viparītānśh cha buddhiḥ sā pārtha tāmasī",
  "dhṛtyā yayā dhārayate manaḥ-prāṇendriya-kriyāḥ yogenāvyabhichāriṇyā dhṛtiḥ sā pārtha sāttvikī",
  "yayā tu dharmakāmārthān dhṛtyā dhārayate 'rjuna prasangen phalākāṅkṣhī dhṛtiḥ sā pārtha rājasī",
  "yayā svapnaṁ bhayaṁ śokaṁ viṣādaṁ madameva cha na vimuñchati durmedhā dhṛtiḥ sā pārtha tāmasī",
  "sukhaṁ tvidānīṁ trividhaṁ śhṛiṇu me bharatarṣhabha abhyāsādramaṭe yatra duḥkhāntaṁ cha nigachchhati",
  "yattadagre viṣhamiva pariṇāme'mṛtopamam tatsukhaṁ sāttvikaṁ proktamātmabuddhiprasādajam",
  "viṣayendriya saṁyogād yattadagre'mṛtopamam pariṇāme viṣhamiva tatsukhaṁ rājasaṁ smṛtam",
  "yadagre chānubandhe cha sukhaṁ mohanamātmanaḥ nidrālasyapramādotthaṁ tattāmasamudāhṛtam",
  "Na tadasti pṛthivyāṁ vā divi deveṣhu vā punaḥ, Sattvaṁ prakṛtijairmuktaṁ yadebhiḥ syāttribhirguṇaiḥ.",
  "Brāhmaṇakṣhatriyaviśhāṁ śhūdrāṇāṁ cha parantapa, Karmāṇi pravibhaktāni svabhāvaprabhavairguṇaiḥ.",
  "Shamaḥ damas tapaḥ śaucaṁ kṣāntir ārjavam eva cha, Jñānaṁ vijñānam āstikyaṁ brahma-karma svabhāvajam",
  "Shauryaṁ tejo dhṛitiḥ dākṣyaṁ yuddhe chāpyapalāyanam, Dānam īśvara-bhāvaścha kṣhātraṁ karma svabhāvajam",
  "kṛṣi-gaurakṣya-vāṇijyaṁ vaiśya-karma svabhāvajam, paricaryātmakaṁ karma śūdrasyāpi svabhāvajam",
  "sve sve karmaṇyabhirataḥ saṁsiddhiṁ labhate naraḥ, svakarmanirataḥ siddhiṁ yathā vindati tacchṛṇu",
  "Yatah pravrittir bhutānām yena sarvam idam tatam, Svakarmaṇā tamabhyarchya siddhiṁ vindati mānavah.",
  "śreyān svadharmo viguṇaḥ paradharmāt svanuṣṭhitāt, svabhāvaniyataṁ karma kurvannāpnoti kilbiṣam",
  "sahajaṁ karma kaunteya sad oṣhamapi na tyajet, sarvārambhā hi doṣheṇa dhūmenāgnirivāvṛtāḥ",
  ];

List<String> chapter_18_english = [
"Arjuna said: O mighty-armed one, I wish to understand the principles of renunciation and the nature of the renounced order of life. O Hrishikesha, please explain these to me separately.",
  "The Supreme Lord said: The wise know that giving up actions that are motivated by desire is renunciation, and they call the giving up of the fruits of all actions the renunciation of the results of action.",
  "Some learned men declare that all kinds of work should be given up as faulty, while others say that acts of sacrifice, charity, and penance should not be abandoned.",
  "O best of the Bharatas, now please listen to me and my conclusive words on the matter of renunciation. Renunciation of material desires is certainly the highest renunciation, and it is of threefold nature, as I will now explain.",
  "Acts of sacrifice, charity, and penance should never be abandoned; they must be performed. Indeed, sacrifice, charity, and penance purify even the great souls.",
  "Furthermore, O Arjuna, it is my supreme and conclusive opinion that all actions should be performed without attachment to the results. This is my final and best instruction to you.",
  "However, giving up actions completely out of delusion is not appropriate for one who is seeking perfection. Such renunciation is said to be in the mode of ignorance."
  "One should give up actions that are motivated by pain alone, and also those that cause physical strain and fear. Renunciation performed in this way is said to be in the mode of passion and is not productive of any real benefit.",
  "O Arjuna, that action which is performed with a sense of duty, without attachment to the results, is considered a sattvic (pure) form of renunciation.",
  "One who does not hate unpleasant work, nor is attached to enjoyable work, such a person is a renunciant (tyāgī), a person of steady intellect (medhāvī), and free from doubts (chinnasaṁśayaḥ), being situated in the mode of goodness (sattva).",
  "Indeed, it is not possible for one embodied to completely renounce all actions. But those who renounce the fruits of their actions, they are called true renunciants.",
  "The results of actions are of three kinds - unpleasant, pleasant, and mixed. But for those who have renounced, after death, there is no bondage to the results of actions, nor for the renunciants at any time.",
  "O mighty-armed Arjuna, understand from Me these five factors that are the cause of all actions, as described in the Sāṅkhya philosophy at the end of their analysis, for the attainment of perfection in all endeavors.",
  "The body, the doer, the various senses, the different activities, and the fifth factor, the divine influence—these are the five factors of action.",
  "By the body, speech, and mind, whatever action a person initiates, these five factors are its causes—either in accordance with righteousness or contrary to it.",
  "But the ignorant person, with an untrained mind, fails to perceive the true nature of the self as the sole doer, even though it is so.",
  "One who has no sense of ego, whose intellect is not tainted, even though engaged in killing, such a person neither kills nor is bound by the action of killing in this world.",
  "Knowledge, the object of knowledge, and the knower are the three factors that motivate action. The instruments of action, the action itself, and the doer are the three constituents of action.",
  "Knowledge, action, and the doer are indeed of three types, according to the distinctions of the modes of material nature. Hear about them as they are described according to the divisions of the modes of nature.",
  "Understand that knowledge to be in the mode of goodness (sattvic) by which one sees the undivided, imperishable reality in all beings, even amidst their diverse manifestations.",
  "Know that knowledge to be in the mode of passion (rājasic) by which one sees various existences as separate and distinct. Such knowledge perceives individuality in all beings.",
  "But that which attaches one to a specific action as if it were the entirety, without considering the cause and effect, without considering the truth, and with little understanding—know that to be in the mode of ignorance (tāmasa).",
  "That action which is performed without attachment, without aversion, and without craving for rewards, and which is performed with proper understanding and determination, is declared to be in the mode of goodness (sattvic).",
  "But that action which is performed with selfish desires and egoistic intentions, and with excessive efforts and exertion, is declared to be in the mode of passion (rājasic).",
  "But that action which is undertaken with delusion, disregarding the consequences, without considering the loss, injury, and one's own capability, is declared to be in the mode of ignorance (tāmasa).",
  "The performer who is free from attachment, non-egotistical, firm, enthusiastic, unaffected by success or failure, is declared to be in the mode of goodness (sattvic).",
  "The performer who is attached, desirous of rewards, greedy, engaging in harmful actions, impure, filled with joy and sorrow, is declared to be in the mode of passion (rājasic).",
  "The performer who is devoid of intelligence, unrefined, stubborn, deceitful, lazy, disheartened, and procrastinating, is declared to be in the mode of ignorance (tāmasa).",
  "O Arjuna, listen to the threefold division of intellect, determination, and the modes of nature, as explained in detail and separately.",
  "That understanding which knows what ought to be done and what ought not to be done, what is to be feared and what is not to be feared, what results in bondage and what leads to liberation, that understanding is considered to be in the mode of goodness (sattvic), O Partha.",
  "That understanding by which one perceives right and wrong, what should be done and what should not be done, improperly and without proper knowledge, that understanding is considered to be in the mode of passion (rājasic), O Partha.",
  "That understanding which considers unrighteousness as righteousness and sees everything upside down, that understanding is considered to be in the mode of ignorance (tāmasa), O Partha.",
  "That firmness by which the mind, vital energy, and senses are controlled, and which is unwavering in the practice of yoga, that firmness is considered to be in the mode of goodness (sattvic), O Partha.",
  "But that determination by which one holds onto duty, desire, and wealth with attachment, O Arjuna, seeking rewards, that determination is considered to be in the mode of passion (rājasic).",
  "But that determination by which one holds onto delusion, fear, sorrow, and despair, and indulges in intoxication, O Partha, that determination is considered to be in the mode of ignorance (tāmasic).",
  "Now, O best of the Bharatas, hear from me about the three types of happiness. By which one attains the end of sorrow, that happiness born of practice.",
  "That which appears like poison at first but tastes like nectar in the end, that happiness is considered to be in the mode of goodness (sāttvic). It arises from the purity of one's intellect and brings clarity and tranquility to the self.",
  "That happiness which arises from the contact of the senses with their objects, which appears like nectar at first but turns into poison in the end, that happiness is considered to be in the mode of passion (rājasic).",
  "That happiness which deludes the self in the beginning and in the sequel, which arises from sleep, indolence, and negligence, that happiness is considered to be in the mode of ignorance (tāmasic).",
  "That which does not exist on the earth, in the celestial abode, or among the gods, and which is beyond the three modes of material nature (sattva, rajas, tamas), that pure consciousness which is free from the material modes of nature is not present.",
  "O Parantapa, the actions of Brahmins, Kshatriyas, Vaishyas, and Shudras are divided according to the qualities born of their own nature.",
  "Peacefulness, self-control, austerity, purity, tolerance, honesty, knowledge, wisdom, and religiousness—these are the natural qualities of actions arising from one's own nature.",
  "Valor, power, determination, skill in battle, and the ability to retreat are the qualities of the Kshatriya born of their inherent nature. Generosity and leadership are also their natural duties.",
  "Agriculture, cattle rearing, and trade are the natural occupations of the Vaisyas born of their inherent nature. Service-oriented work is the natural duty of the Shudras as well.",
  "A person attains perfection by being engaged in their prescribed duties. Hear from me how one who is dedicated to their own duty achieves perfection.",
  "By whom all this universe is pervaded through their manifestation, from whom all beings are born, by performing their prescribed duties with devotion, humans attain perfection.",
  "One's own duty performed imperfectly is better than the duty of another well-performed. By performing actions according to one's nature, one does not incur sin.",
  "O Kaunteya (Arjuna), one should not give up their natural duties, even if they are imperfect. All undertakings are covered with some fault, just as fire is covered by smoke.",
];