List<String> chapter_four_trans_sanskrit = [
  "Imam vivasvate yogam proktavan aham avyayam Vivasvan manave praha manur ikshvakave 'bravit",
  "Evam paramparā-prāptam Imam rājarṣayo viduḥ Sa kāleneha mahatā Yogo naṣṭaḥ parantapa",
  "Sa evāyaṁ mayā te'dya yogaḥ proktaḥ purātanaḥ Bhakto'si me sakhā cheti rahasyaṁ hyetad uttamam",
  "Arjuna uvācha: Aparaṁ bhavato janma, paraṁ janma vivasvataḥ Katham etad vijānīyāṁ tvam ādau proktavān iti.",
  "śrī bhagavān uvāca bahūni me vyatītāni janmāni tava cārjuna tānyahaṃ veda sarvāṇi na tvaṃ vettha parantapa",
  "ajo 'pi sann avyayātmā bhūtānām īśvaro 'pi san prakṛtiṁ svāmadhiṣṭhāya saṁbhavāmy ātma-māyayā",
  "yadā yadā hi dharmasya glānir bhavati bhārata abhyutthānam adharmasya tadātmānaṁ sṛjāmy aham",
  "paritrāṇāya sādhūnāṁ vināśāya ca duṣkṛtām dharma-saṁsthāpanārthāya sambhavāmi yuge yuge",
  "janma karma ca me divyam evaṁ yo vetti tattvataḥ tyaktvā dehaṁ punar janma naiti mām eti so 'rjuna",
  "vīta-rāga-bhaya-krodhā man-mayā mām upāśritāḥ bahavo jñāna-tapasā pūtā mad-bhāvam āgatāḥ",
  "ye yathā māṁ prapadyante tāṁs tathaiva bhajāmyaham mama vartmānuvartante manuṣyāḥ pārtha sarvaśaḥ",
  "kāṅkṣantaḥ karmaṇāṁ siddhiṁ yajanta iha devatāḥ kṣipraṁ hi mānuṣe loke siddhir bhavati karmajā",
  "chaturvarnyam maya srstam guna-karma-vibhagashah tasya kartaram api mam viddhy akartaram avyayam",
  "na māṁ karmāṇi limpanti na me karmaphale spṛhā iti māṁ yo 'bhijānāti karmabhir na sa badhyate",
  "evaṁ jñātvā kṛtaṁ karma pūrvair api mumukṣubhiḥ kuru karmaiva tasmāttvaṁ pūrvaiḥ pūrvataraṁ kṛtam",
  "Kim karma kim akarmeti kavayo'pyatra mohitāh, Tatte karma pravakshyāmi yaj jnātvā mokshyase 'śubhāt",
  "Karmano hyapi boddhavyam boddhavyam cha vikarmanah. Akarmanashcha boddhavyam gahana karmano gatih",
  "Karmaṇyakarma yaḥ paśyed akarmaṇi ca karma yaḥ sa buddhimān manuṣyeṣu sa yuktaḥ kṛtsnakarma-kṛt",
  "Yasya sarve samārambhāḥ kāma-saṅkalpa-varjitāḥ Jñānāgni-dagdha-karmāṇaṁ tamāhuḥ paṇḍitaṁ budhāḥ.",
  "tyaktvā karma-phalāsaṅgaṁ nitya-tṛpto nirāśrayaḥ karmaṇy-abhipravṛtto’pi naiva kiñcit karoti saḥ",
  "nirāśīr yata-cittātmā tyakta-sarva-parigrahaḥ śāriram kevalaṁ karma kurvannāpnoti kilbiṣam",
  "yadṛcchā-lābha-santuṣṭo dvandvātīto vimatsaraḥ samaḥ siddhāvasiddhau cha kṛtvāpi na nibadhyate",
  "gatasangasya muktasya jnanavasthitachetasah, yajnayacaratah karma samagram praviliyate",
  "Brahmārpaṇaṃ Brahma havirbrahmāgnau Brahmaṇā hutam Brahmaiva tena gantavyaṃ Brahmakarmasamādhinā",
  "daivamevapare yajñaṃ yoginaḥ paryupāsate, brahmāgnāvapare yajñaṃ yajñenaivopajuhvati" // --25
];

List<String> chapter_four_english = [
  "The Supreme Lord said: I taught this imperishable yoga to the sun-god, Vivasvan, and Vivasvan instructed it to Manu, the father of mankind, and Manu in turn instructed it to Ikshvaku. This is the famous verse from the Bhagavad Gita where Lord Krishna describes the lineage of the ancient teachings of yoga.",
  "The verse explains that the science of yoga was once well-understood and passed down through a lineage of saintly kings, but as time passed, the chain of succession was broken, and the knowledge of yoga was lost.",
  "Lord Krishna tells Arjuna that he is revealing the ancient knowledge of yoga to him because they have a close relationship and the knowledge was lost over time.",
  "Your birth is recent, while the birth of Vivasvan, the sun-god, is ancient. How am I to understand that you instructed him in the beginning?",
  "The Blessed Lord said: Many, many births both you and I have passed. I can remember all of them, but you cannot, O subduer of the enemy!",
  "Although I am unborn and My transcendental body never deteriorates, and although I am the Lord of all beings, I still appear in every millennium in My original transcendental form, by My own internal potency.",
  "Whenever and wherever there is a decline in religious practice, O Arjuna, and a predominant rise of irreligion—at that time I descend Myself.",
  "For the deliverance of the pious and the destruction of the miscreants, as well as for the establishment of religious principles, I advent Myself in every millennium.",
  "One who understands the divine nature of My birth and activities, O Arjuna, upon leaving the body, attains Me and does not take birth again in this material world.",
  "Being freed from attachment, fear, and anger, being fully absorbed in Me and taking refuge in Me, purified by the austerity of knowledge, many have attained My Being.",
  "As they surrender unto Me, I reward them accordingly. Everyone follows My path in all respects, O son of Pritha.",
  "People desiring success in their actions worship the celestial gods here. For success in action quickly arises in this human world through actions born of nature.",
  "The four categories of occupation were created by Me according to people’s natures and activities. Although I am the creator of this system, know Me to be the non-doer and eternal.",
  "Actions do not cling to me, nor do I desire their fruits. One who knows me in this way is never entangled by action.",
  "Having understood this (the nature of karma and its effects), even those who seek liberation (moksha) have performed action before. Therefore, you too perform your duty (karma) established by tradition, as did the ancients.",
  "Even the wise are confused about what is action and what is inaction. I shall explain to you what action is, knowing which you shall be liberated from the bondage of karma. ",
  "One must understand the nature of work, the nature of forbidden work, and also the nature of inaction. The path of work is mysterious.",
  "He who sees inaction in action, and action in inaction, he is intelligent among men, and he is in the transcendental position, although engaged in all sorts of activities.",
  "Those who have given up all desires and have become free from all sense of proprietorship and false ego, and whose actions have been burnt up by the fire of perfect knowledge—such sages are called learned and wise."
  "Abandoning attachment to the fruits of actions, always content, and without dependence, even though engaged in action, one does nothing at all.",
  "One who is without desire, with a pure mind, free from all attachment and egoism, and performs actions only with the body, is not tainted by sin even while performing actions."
  "One who is satisfied with what comes of its own accord, who is free from dualities and envy, and who is equal in success and failure, though engaged in actions, is not bound by them.",
  "For the one who is free from attachment and whose mind is established in knowledge, performing actions as an offering to the Divine, the entire act of work is dissolved.",
  "The act of offering is Brahman, the oblation is Brahman, offered by Brahman in the fire of Brahman. Brahman alone is to be reached by him who is firmly established in Brahman through the performance of actions.",
  "Some yogis worship the gods with sacrifices, while others offer the self as sacrifice by the fire of the Brahman through yoga."
];