List<String> chapter_ten_trans_sanskrit = [
  "śrībhagavān uvāca, bhūya eva mahābāho śṛṇu me paramaṃ vacaḥ, yat te 'haṃ prīyamāṇāya vakṣyāmi hitakāmyayā ॥",
  "na me viduḥ suragaṇāḥ prabhavaṃ na maharṣayaḥ ahamādir hi devānāṃ maharṣīṇāṃ ca sarvaśaḥ",
  "yo māmajam anādiṃ ca vetti lokamaheshvaram asammūḍhaḥ sa martyeṣu sarvapāpaiḥ pramucyate",
  "buddhir jnana masammohah kshama satyam damah shamah sukham duhkham bhavo 'bhavo bhayam cabhayam eva ca",
  "ahimsā samatā tuṣṭis tapo dānaṃ yaśo'yaśaḥ bhavanti bhāvā bhūtānāṃ matta eva pṛthag-vidhāḥ",
  "maharṣayaḥ saptapūrve caturāro manavastathā madbhāvā mānasā jātā yeṣāṃ loka imāḥ prajāḥ",
  "etāṁ vibhūtiṁ yogaṁ ca mama yo vetti tattvataḥ so'vikampena yogena yujyate nātra saṁśayaḥ",
  "aham sarvasya prabhavo mattah sarvam pravartate iti matva bhajante mam budha bhava-samanvitah",
  "Machchittā mad-gata-prāṇā bodhayantaḥ parasparam Kathayantaśca māṁ nityaṁ tuṣhyanti ca ramanti ca",
  "Teṣāṁ satata-yuktānāṁ bhajatāṁ prīti-pūrvakam Dadāmi buddhi-yogaṁ taṁ yena mām upayānti te.",
  "Teshām evānukampārtham aham ajñāna-jaṁ tamaḥ nāśayāmy ātma-bhāva-stho jñāna-dīpena bhāsvatā",
  "arjuna uvāca paraṁ brahma paraṁ dhāma pavitraṁ paramaṁ bhavān puruṣaṁ śāśvataṁ divyam ādi-devam ajaṁ vibhum",
  "āhus tvām ṛṣayaḥ sarve devarṣir nāradastathā asito devalo vyāsaḥ svayaṃ caiva bravīṣi me",
  "sarvam etad ritam manye yan mam vadasi keshava na hi te bhagavan vyaktim vidur deva na danavah",
  "Svayamevaatmanaatmaanam vetha twam purushottama Bhootabhaavana bhootesha devadeva jagatpate",
  "vakṭum arhasyaśeṣeṇa divyā hyātmavibhūtayaḥ yābhir vibhūtibhir lokān imāṃs tvaṃ vyāpya tiṣhṭhasi",
  "Katham vidyām ahaṁ yogiṁs tvaṁ sadā paricintayan Keṣu keṣu ca bhāveṣu cintyo'si bhagavan mayā.",
  "Vistareṇātmano yogaṁ vibhūtiṁ ca janārdana Bhūyaḥ kathaya tṛptir hi śṛṇvato nāsti me'mṛtam.",
  "Shri Bhagavan uvacha, hanta te kathayishyami divya hyatmavibhutayah, pradhanyatah kurushreshtha nastyanto vistarasyme.",
  "Aham atma gudakesha sarva-bhutashaya-sthitah, aham adishcha madhyam cha bhutanam anta eva cha.",
  "Adityanamaham vishnur jyotisham raviramshuman, marichir marutam asmi nakshatranamaham shashi.",
  "Vedanam samavedo'smi devanamasmi vasavah, indriyanam manashchasm bhutanam asmi chetana.",
  "Rudranam shankarashchasmi vitthesho yaksharakshasam, vasunam pavakashchasmi meruh shikharinamaham.",
  "Purodhasam cha mukhyam mam viddhi Partha Brihaspatim, senaninam aham Skandah sarasam asmi sagarah.",
  "Maharshiṇāṁ bhṛgurahaṁ girāmasmyekamakṣaram, Yajñānāṁ japayajño'smi sthāvarāṇāṁ himālayaḥ",
  "Aśvatthaḥ sarvavṛkṣāṇāṁ devarṣīṇāṁ cha nāradaḥ, Gandharvāṇāṁ chitrarathaḥ siddhānāṁ kapilo muniḥ",
  "Uccaiḥśravasam-aśvānām viddhi mām amṛtodbhavam, Airāvataṁ gajendrāṇāṁ narāṇāṁ cha narādhipam",
  "Āyudhānām-aham vajraṁ dhenuunām-asmi kāmadhuk, Prajanaś-chāsmi kandarpaḥ sarpāṇām-asmi vāsukiḥ",
  "Anantaś-chāsmi nāgānāṁ varuṇo yādasām-aham, Pitṝṇām-aryamā chāsmi yamaḥ saṁyamatām-aham",
  "Prahlādaś-chāsmi daityānām kālaḥ kalayatām-aham, Mṛgāṇāṁ cha mṛgendro-aham vainateyaś-cha pakṣiṇām",
  "Pavanaḥ pavatām-asmi Rāmaḥ śastrabhṛtām-aham, Jhaṣhāṇāṁ makaraś-chāsmi srotasām-asmi jāhnavī",
  "Sargāṇām ādir-antaś cha madhyam chaivāham arjuna, Adhyātma-vidyā vidyānām vādaḥ pravadatām aham",
  "akṣarāṇāmakāro'smi dvandvaḥ sāmāsikasya ca ahamevākṣayaḥ kālo dhātāhaḿ viśvatomukhaḥ",
  "mṛtyuḥ sarvaharaś cāham udbhavaś ca bhaviṣyatām, kīrtiḥ śrīrvāk ca nārīṇām smṛtir medhā dhṛtiḥ kṣamā",
  "bṛhatsāma tathā sāmnāṃ gāyatrī chandhasāmaham māsānāṃ mārgaśīrṣo'hamṛtūnāṃ kusumākaraḥ",
  "dyūtaṃ chalayatāmasmi tejas tejasvinām aham jayo’smi vyavasāyo’smi sattvaṃ sattvavatām aham",
  "vṛṣṇīnāṃ vāsudevō'smi pāṇḍavānāṃ dhanañjayaḥ, munīnāmapyaham vyāsaḥ kavīnāmuśanā kaviḥ",
  "Daṇḍo damayatām asmi nītirasmi jigīṣatām, Maunaṃ caivāsmi guhyānāṃ jñānaṃ jñānavatām aham",
  "yacchāpi sarvabhūtānām bījaṃ tadahamarjuna na tadasti vinā yatsyānmayā bhūtaṃ carācaram",
  "Na anto'sti mama divyaanaam vibhootiinaam parantapa; esha tuuddeshatah prokto vibhuutervistaro maya.",
  "yadyad vibhūtimat sattvaṁ śrīmadoorjitameva vā tattadevāvagaccha tvaṁ mama tejo-'śasambhavam",
  "athavā bahunaitena kiṁ jñātena tavārjuna viṣṭabhyāhamidaṁ kṛtsnam ekāṁśena sthito jagat",
  ];



List<String> chapter_ten_english = [
  "Śrī Bhagavān said: Again, O mighty-armed Arjuna, listen to My supreme word, which I shall speak to you who are dear to Me for your benefit.",
  "The demigods do not know my origin, nor do the great sages. I am the source of all demigods and sages.",
  "He who knows Me as the unborn, as the beginningless, as the Supreme Lord of all the worlds—he, undeluded among men, is freed from all sins.",
  "Buddhi (intellect), jnana (knowledge), asammoha (clarity), kshama (forgiveness), satya (truth), dama (self-control), shama (mental peace), sukha (happiness), dukha (distress), bhava (birth), abhava (death), bhaya (fear), and abhaya (fearlessness) - all these are nothing but the Supreme Being.",
  "Non-violence, equanimity, contentment, penance, charity, fame and infamy, these states of being of creatures arise from Me alone, separately.",
  "Seven great sages and four Manus, as well as their mental creations, have sprung from My mind, and all the creatures in these planets descend from them.",
  "Whoever understands in truth this my glory and yoga, becomes united with it unshakenly by means of unwavering yoga; there is no doubt about it.",
  "I am the source of all, from Me everything originates. The wise who know this worship Me with loving devotion.",
  "With their minds focused on me and their lives surrendered to me, enlightening one another and talking about me constantly, they are contented and delighted.",
  "To those who are constantly devoted and worship Me with love, I give the understanding by which they can come to Me.",
  "To show them special mercy, I, dwelling in their hearts, destroy with the shining lamp of knowledge the darkness born of ignorance.",
  "Arjuna said: \"You are the Supreme Brahman, the ultimate, the supreme abode and purifier, the Absolute Truth and the eternal divine person. You are the primal God, transcendental and original, and You are the unborn and all-pervading beauty.\"",
  "The sages, along with the divine sage Narada, Asita, Devala, and Vyasadeva, all proclaim this of You. And now You Yourself are declaring it to me.",
  "O Keshava, I believe that all that You have said to me is true. O Lord, neither the gods nor the demons comprehend Your manifestations.",
  "You, O Supreme Person, know Yourself by Yourself. You are the Lord of all creatures, the Creator of all, the God of gods, the Supreme controller of the universe.",
  "Please describe in detail Your divine glories, by which You pervade all these worlds by Your manifestations. O Lord, by expanding Your transdental form, You always reside in them.",
  "How should I know you, O Yogi, ever steadfast in concentration? In what aspects and forms are you to be meditated on, O blessed Lord?",
  "Tell me again in detail, O Janardana (Krishna), of Your mighty powers and glories, for I never tire of hearing Your nectar-like words.",
  "Shri Bhagavan said, \"O Kurusreshta (best among the Kurus)! I shall now tell you about the divine manifestations of the Self. However, there is no end to the extent of my greatness, and therefore, I shall only speak briefly.\"",
  "Lord Krishna said, \"O Arjuna, I am the Self, situated within all beings. I am the beginning, the middle, and also the end of all beings.\"",
  "Lord Krishna said, \"Among the Adityas, I am Vishnu; among the luminaries, I am the radiant sun. Among the Maruts, I am Marichi, and among the stars, I am the moon.\"",
  "Lord Krishna said, \"Among the Vedas, I am the Sama Veda; among the gods, I am Indra. Among the senses, I am the mind, and among living beings, I am consciousness.\"",
  "Lord Krishna said, \"Among the Rudras, I am Shankara; among the Yakshas and Rakshasas, I am the lord of wealth. Among the Vasus, I am the fire god, and among the mountains, I am Meru.\"",
  "Lord Krishna said, \"Know me to be the chief among priests, O Arjuna, and among the commanders of armies, I am Skanda. Among bodies of water, I am the ocean.\"",
  "Of the great sages I am Bhṛgu; of vibrations I am the transcendental oṁ. Of sacrifices I am the chanting of the holy names [japa], and of immovable things I am the Himalayas.",
  "Of all trees I am the banyan tree; of the sages among the demigods I am Nārada. Of the celestial musicians I am Citraratha, and among the perfected beings I am the sage Kapila.",
  "Among horses know me to be Uccaiḥśravas, born of the nectar ocean. Of lordly elephants I am Airāvata, and among men I am the monarch.",
  "Of weapons I am the thunderbolt; among cows I am the surabhi. Of procreators I am Kandarpa, the god of love, and of serpents I am Vāsuki, the chief.",
  "Of the many hooded Nagas, I am Ananta. Among the aquatic beings I am Varuna, and of the manes I am Aryama. Among subduers I am Yama, the lord of death.",
  "Of demons I am Prahlada, and of reckoners of time I am Time himself. Of beasts I am the lion, and of birds I am Garuda, the son of Vinata.",
  "Of the purifiers, I am the wind, and of the wielders of weapons, I am Rama. Of fishes, I am the shark, and of flowing rivers, I am the Ganges.",
  "Of creations, I am the beginning, end, and middle, O Arjuna. Of all sciences, I am the science of the self, and of all debates, I am the logical conclusion.",
  "I am the letter \"A\" among the alphabets, and the dual among the compounds. I am indeed inexhaustible time, and I am the Creator facing in all directions.",
  "I am Death, who takes away everything, and I am also the source of future creations. Among feminine qualities, I am fame, speech, memory, intelligence, steadfastness, and forgiveness.",
  "I am the Brihat Sama among the Sama mantras, and Gayatri among the meters, Among months, I am Margashirsha, and among seasons, I am the flower-bearing spring.",
  "I am the gambling of the deceitful; I am the splendor of the splendid. Among things that conquer, I am victory; I am the determination of the resolute.",
  "I am Vasudeva among the Vrishnis, and Dhananjaya among the Pandavas. Among the sages I am Vyasa, and among poets I am Usana.",
  "I am the punishment of the lawbreakers, and the victory of the victorious. I am the silence of secrets, and the knowledge of the knowledgeable.",
  "O Arjuna, I am the seed of all beings. There is nothing, animate or inanimate, that can exist without me.",
  "There is no end to My divine manifestations, O Arjuna. What I have mentioned is only a sample of My infinite glory.",
  "Whatever is glorious, beautiful, and mighty, know that to be a manifestation of a part of my splendor.",
  "Or what need is there, Arjuna, for all this detailed knowledge? With a single fragment of Myself I pervade and support this entire universe.",
];